package com.study.ethwallet.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.study.ethwallet.entity.ETHWallet;
import com.study.ethwallet.entity.Coin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eTHWalletDaoConfig;
    private final DaoConfig coinDaoConfig;

    private final ETHWalletDao eTHWalletDao;
    private final CoinDao coinDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eTHWalletDaoConfig = daoConfigMap.get(ETHWalletDao.class).clone();
        eTHWalletDaoConfig.initIdentityScope(type);

        coinDaoConfig = daoConfigMap.get(CoinDao.class).clone();
        coinDaoConfig.initIdentityScope(type);

        eTHWalletDao = new ETHWalletDao(eTHWalletDaoConfig, this);
        coinDao = new CoinDao(coinDaoConfig, this);

        registerDao(ETHWallet.class, eTHWalletDao);
        registerDao(Coin.class, coinDao);
    }
    
    public void clear() {
        eTHWalletDaoConfig.clearIdentityScope();
        coinDaoConfig.clearIdentityScope();
    }

    public ETHWalletDao getETHWalletDao() {
        return eTHWalletDao;
    }

    public CoinDao getCoinDao() {
        return coinDao;
    }

}
