package com.study.ethwallet.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.study.ethwallet.entity.ETHWallet;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ETHWallet".
*/
public class ETHWalletDao extends AbstractDao<ETHWallet, Long> {

    public static final String TABLENAME = "ETHWallet";

    /**
     * Properties of entity ETHWallet.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CoinId = new Property(0, Long.class, "coinId", true, "COIN_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Password = new Property(2, String.class, "password", false, "PASSWORD");
        public final static Property KeystorePath = new Property(3, String.class, "keystorePath", false, "KEYSTORE_PATH");
        public final static Property Mnemonic = new Property(4, String.class, "mnemonic", false, "MNEMONIC");
        public final static Property IsCurrent = new Property(5, Boolean.class, "isCurrent", false, "IS_CURRENT");
        public final static Property IsBackup = new Property(6, Boolean.class, "isBackup", false, "IS_BACKUP");
    }

    private DaoSession daoSession;


    public ETHWalletDao(DaoConfig config) {
        super(config);
    }
    
    public ETHWalletDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ETHWallet\" (" + //
                "\"COIN_ID\" INTEGER PRIMARY KEY ," + // 0: coinId
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"PASSWORD\" TEXT NOT NULL ," + // 2: password
                "\"KEYSTORE_PATH\" TEXT," + // 3: keystorePath
                "\"MNEMONIC\" TEXT," + // 4: mnemonic
                "\"IS_CURRENT\" INTEGER," + // 5: isCurrent
                "\"IS_BACKUP\" INTEGER);"); // 6: isBackup
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ETHWallet\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ETHWallet entity) {
        stmt.clearBindings();
 
        Long coinId = entity.getCoinId();
        if (coinId != null) {
            stmt.bindLong(1, coinId);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getPassword());
 
        String keystorePath = entity.getKeystorePath();
        if (keystorePath != null) {
            stmt.bindString(4, keystorePath);
        }
 
        String mnemonic = entity.getMnemonic();
        if (mnemonic != null) {
            stmt.bindString(5, mnemonic);
        }
 
        Boolean isCurrent = entity.getIsCurrent();
        if (isCurrent != null) {
            stmt.bindLong(6, isCurrent ? 1L: 0L);
        }
 
        Boolean isBackup = entity.getIsBackup();
        if (isBackup != null) {
            stmt.bindLong(7, isBackup ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ETHWallet entity) {
        stmt.clearBindings();
 
        Long coinId = entity.getCoinId();
        if (coinId != null) {
            stmt.bindLong(1, coinId);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getPassword());
 
        String keystorePath = entity.getKeystorePath();
        if (keystorePath != null) {
            stmt.bindString(4, keystorePath);
        }
 
        String mnemonic = entity.getMnemonic();
        if (mnemonic != null) {
            stmt.bindString(5, mnemonic);
        }
 
        Boolean isCurrent = entity.getIsCurrent();
        if (isCurrent != null) {
            stmt.bindLong(6, isCurrent ? 1L: 0L);
        }
 
        Boolean isBackup = entity.getIsBackup();
        if (isBackup != null) {
            stmt.bindLong(7, isBackup ? 1L: 0L);
        }
    }

    @Override
    protected final void attachEntity(ETHWallet entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ETHWallet readEntity(Cursor cursor, int offset) {
        ETHWallet entity = new ETHWallet( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // coinId
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // password
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // keystorePath
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mnemonic
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // isCurrent
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0 // isBackup
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ETHWallet entity, int offset) {
        entity.setCoinId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setPassword(cursor.getString(offset + 2));
        entity.setKeystorePath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMnemonic(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsCurrent(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setIsBackup(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ETHWallet entity, long rowId) {
        entity.setCoinId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ETHWallet entity) {
        if(entity != null) {
            return entity.getCoinId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ETHWallet entity) {
        return entity.getCoinId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
